# Generated by Django 3.2 on 2021-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('binance_key', models.CharField(max_length=64)),
                ('binance_secret_key', models.CharField(max_length=64)),
            ],
        ),
    ]
